# Generated by Django 3.2.25 on 2024-12-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('multimedia', models.FileField(upload_to='multimedia/')),
            ],
        ),
    ]
