# Generated by Django 3.2.25 on 2024-12-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_childprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='user_profile.childprofile')),
            ],
        ),
    ]
