# Generated by Django 3.2.25 on 2024-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20241224_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='user_profile.Interest'),
        ),
    ]
